#!/usr/bin/env python3
  
"""
    Power on the Lidar
"""

import rospy
from time import sleep
from gpiozero import LED

def main():
    rospy.init_node('lidar_onoff')
    nodename = rospy.get_name()
    rospy.loginfo("%s started" % nodename)

    output = LED(5)

    rospy.loginfo(rospy.get_caller_id() + " Turning Lidar on")
    output.on()

    rospy.spin()

    output.off()
    rospy.loginfo(rospy.get_caller_id() + " Turning Lidar off")
    output.off()
    sleep(1)


if __name__ == '__main__':
    main()



