#!/usr/bin/env python3
  
"""
    Power on the Lidar
"""

from time import sleep
from gpiozero import LED
import signal
import warnings

run = True

def signal_handling(signum, frame):           
    global run                        
    run = False

def main():
    print("Turning Lidar on")

    warnings.filterwarnings("ignore", message="Falling back from")

    output = LED(5)
    output.on()

    signal.signal(signal.SIGINT, signal_handling)

    while run:
        sleep(0.2)

    sleep(1)
    print("Turning Lidar off")
    output.off()

if __name__ == '__main__':
    main()



